// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_ASP_Book.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323101101_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AuthorEntity", b =>
                {
                    b.Property<int>("IdAuthor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdAuthor");

                    b.ToTable("t_author");

                    b.HasData(
                        new
                        {
                            IdAuthor = 1,
                            FirstName = "J.K.",
                            LastName = "Rowling"
                        },
                        new
                        {
                            IdAuthor = 2,
                            FirstName = "J.R.R.",
                            LastName = "Tolkien"
                        },
                        new
                        {
                            IdAuthor = 3,
                            FirstName = "George R.R.",
                            LastName = "Martin"
                        },
                        new
                        {
                            IdAuthor = 4,
                            FirstName = "Isaac",
                            LastName = "Asimov"
                        },
                        new
                        {
                            IdAuthor = 5,
                            FirstName = "Arthur C.",
                            LastName = "Clarke"
                        },
                        new
                        {
                            IdAuthor = 6,
                            FirstName = "Jane",
                            LastName = "Austen"
                        },
                        new
                        {
                            IdAuthor = 7,
                            FirstName = "George",
                            LastName = "Orwell"
                        },
                        new
                        {
                            IdAuthor = 8,
                            FirstName = "Ernest",
                            LastName = "Hemingway"
                        },
                        new
                        {
                            IdAuthor = 9,
                            FirstName = "F. Scott",
                            LastName = "Fitzgerald"
                        },
                        new
                        {
                            IdAuthor = 10,
                            FirstName = "Agatha",
                            LastName = "Christie"
                        });
                });

            modelBuilder.Entity("BookEntity", b =>
                {
                    b.Property<int>("IdBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cover")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EditionYear")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FkAuthor")
                        .HasColumnType("int");

                    b.Property<int>("FkCategory")
                        .HasColumnType("int");

                    b.Property<int>("FkPublisher")
                        .HasColumnType("int");

                    b.Property<int>("FkUser")
                        .HasColumnType("int");

                    b.Property<int?>("NbPage")
                        .HasColumnType("int");

                    b.Property<string>("Passage")
                        .HasColumnType("longtext");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Resume")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdBook");

                    b.HasIndex("FkAuthor");

                    b.HasIndex("FkCategory");

                    b.HasIndex("FkPublisher");

                    b.HasIndex("FkUser");

                    b.ToTable("t_book");

                    b.HasData(
                        new
                        {
                            IdBook = 1,
                            Cover = "cover_hp1.jpg",
                            EditionYear = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkAuthor = 1,
                            FkCategory = 2,
                            FkPublisher = 1,
                            FkUser = 1,
                            NbPage = 223,
                            Passage = "Chapter 1: The Boy Who Lived",
                            Rating = 5,
                            Resume = "Un jeune magicien découvre qu'il est un sorcier et commence ses études à Poudlard.",
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            IdBook = 2,
                            Cover = "cover_lotr1.jpg",
                            EditionYear = new DateTime(1954, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkAuthor = 2,
                            FkCategory = 2,
                            FkPublisher = 2,
                            FkUser = 2,
                            NbPage = 487,
                            Passage = "Chapter 1: A Long-expected Party",
                            Rating = 5,
                            Resume = "Un groupe d'aventuriers entreprend un long voyage pour détruire un anneau magique.",
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            IdBook = 3,
                            Cover = "cover_got1.jpg",
                            EditionYear = new DateTime(1996, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkAuthor = 3,
                            FkCategory = 2,
                            FkPublisher = 3,
                            FkUser = 3,
                            NbPage = 694,
                            Passage = "Prologue",
                            Rating = 4,
                            Resume = "Les nobles familles de Westeros se battent pour le trône du Fer dans un monde de magie et de politique.",
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            IdBook = 4,
                            Cover = "cover_foundation.jpg",
                            EditionYear = new DateTime(1951, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkAuthor = 4,
                            FkCategory = 1,
                            FkPublisher = 4,
                            FkUser = 4,
                            NbPage = 255,
                            Passage = "Chapter 1",
                            Rating = 4,
                            Resume = "Un psychohistorien tente de sauver la civilisation galactique de l'effondrement imminent.",
                            Title = "Foundation"
                        },
                        new
                        {
                            IdBook = 5,
                            Cover = "cover_2001.jpg",
                            EditionYear = new DateTime(1968, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkAuthor = 5,
                            FkCategory = 1,
                            FkPublisher = 5,
                            FkUser = 1,
                            NbPage = 297,
                            Passage = "Part One: TMA-1",
                            Rating = 5,
                            Resume = "Une mission spatiale révèle un mystère cosmique ancien et l'évolution de l'humanité.",
                            Title = "2001: A Space Odyssey"
                        },
                        new
                        {
                            IdBook = 6,
                            Cover = "cover_pp.jpg",
                            EditionYear = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkAuthor = 6,
                            FkCategory = 4,
                            FkPublisher = 6,
                            FkUser = 2,
                            NbPage = 279,
                            Passage = "Chapter 1",
                            Rating = 5,
                            Resume = "L'histoire d'amour entre Elizabeth Bennet et Mr Darcy dans l'Angleterre du XIXe siècle.",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            IdBook = 7,
                            Cover = "cover_1984.jpg",
                            EditionYear = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkAuthor = 7,
                            FkCategory = 5,
                            FkPublisher = 7,
                            FkUser = 3,
                            NbPage = 328,
                            Passage = "Part One, Chapter 1",
                            Rating = 5,
                            Resume = "Un roman dystopique où un gouvernement totalitaire contrôle chaque aspect de la vie.",
                            Title = "1984"
                        },
                        new
                        {
                            IdBook = 8,
                            Cover = "cover_omts.jpg",
                            EditionYear = new DateTime(1952, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkAuthor = 8,
                            FkCategory = 6,
                            FkPublisher = 8,
                            FkUser = 4,
                            NbPage = 127,
                            Passage = "Chapter 1",
                            Rating = 4,
                            Resume = "Un vieux pêcheur cubain lutte contre un grand marlin dans l'océan.",
                            Title = "The Old Man and the Sea"
                        },
                        new
                        {
                            IdBook = 9,
                            Cover = "cover_gg.jpg",
                            EditionYear = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkAuthor = 9,
                            FkCategory = 4,
                            FkPublisher = 9,
                            FkUser = 5,
                            NbPage = 180,
                            Passage = "Chapter 1: In My Younger and More Vulnerable Years",
                            Rating = 4,
                            Resume = "L'histoire de Jay Gatsby et de son obsession pour une femme dans les années 1920.",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            IdBook = 10,
                            Cover = "cover_mooe.jpg",
                            EditionYear = new DateTime(1934, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkAuthor = 10,
                            FkCategory = 3,
                            FkPublisher = 10,
                            FkUser = 1,
                            NbPage = 256,
                            Passage = "Chapter 1",
                            Rating = 4,
                            Resume = "Hercule Poirot enquête sur un meurtre dans un train luxueux bloqué par la neige.",
                            Title = "Murder on the Orient Express"
                        });
                });

            modelBuilder.Entity("CategoryEntity", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdCategory");

                    b.ToTable("t_category");

                    b.HasData(
                        new
                        {
                            IdCategory = 1,
                            Name = "Science-Fiction"
                        },
                        new
                        {
                            IdCategory = 2,
                            Name = "Fantasy"
                        },
                        new
                        {
                            IdCategory = 3,
                            Name = "Mystère"
                        },
                        new
                        {
                            IdCategory = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            IdCategory = 5,
                            Name = "Thriller"
                        },
                        new
                        {
                            IdCategory = 6,
                            Name = "Aventure"
                        },
                        new
                        {
                            IdCategory = 7,
                            Name = "Historique"
                        },
                        new
                        {
                            IdCategory = 8,
                            Name = "Biographie"
                        },
                        new
                        {
                            IdCategory = 9,
                            Name = "Poésie"
                        },
                        new
                        {
                            IdCategory = 10,
                            Name = "Jeunesse"
                        });
                });

            modelBuilder.Entity("CommentEntity", b =>
                {
                    b.Property<int>("IdComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FkBook")
                        .HasColumnType("int");

                    b.Property<int>("FkUser")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("IdComment");

                    b.HasIndex("FkBook");

                    b.HasIndex("FkUser");

                    b.ToTable("t_comment");

                    b.HasData(
                        new
                        {
                            IdComment = 1,
                            Content = "Excellent livre, très captivant!",
                            FkBook = 1,
                            FkUser = 2,
                            Rating = 5
                        },
                        new
                        {
                            IdComment = 2,
                            Content = "Les personnages sont bien développés et l'histoire est magique.",
                            FkBook = 1,
                            FkUser = 3,
                            Rating = 5
                        },
                        new
                        {
                            IdComment = 3,
                            Content = "Une œuvre maîtresse de la science-fiction.",
                            FkBook = 2,
                            FkUser = 4,
                            Rating = 5
                        },
                        new
                        {
                            IdComment = 4,
                            Content = "Difficile à lire par endroits mais extraordinaire.",
                            FkBook = 2,
                            FkUser = 5,
                            Rating = 4
                        },
                        new
                        {
                            IdComment = 5,
                            Content = "Un grand classique, vivement recommandé.",
                            FkBook = 3,
                            FkUser = 1,
                            Rating = 5
                        },
                        new
                        {
                            IdComment = 6,
                            Content = "Incroyable, j'ai adoré chaque page.",
                            FkBook = 4,
                            FkUser = 2,
                            Rating = 5
                        },
                        new
                        {
                            IdComment = 7,
                            Content = "Un classique de la science-fiction, à lire absolument.",
                            FkBook = 5,
                            FkUser = 3,
                            Rating = 5
                        },
                        new
                        {
                            IdComment = 8,
                            Content = "Poétique et philosophique, simplement magnifique.",
                            FkBook = 6,
                            FkUser = 4,
                            Rating = 5
                        },
                        new
                        {
                            IdComment = 9,
                            Content = "Un vrai chef-d'œuvre de la littérature.",
                            FkBook = 7,
                            FkUser = 5,
                            Rating = 5
                        },
                        new
                        {
                            IdComment = 10,
                            Content = "Court mais intense, très beau.",
                            FkBook = 8,
                            FkUser = 1,
                            Rating = 4
                        },
                        new
                        {
                            IdComment = 11,
                            Content = "Fascinant portrait de l'amour et du rêve américain.",
                            FkBook = 9,
                            FkUser = 2,
                            Rating = 4
                        },
                        new
                        {
                            IdComment = 12,
                            Content = "Une intrigue palpitante du début à la fin.",
                            FkBook = 10,
                            FkUser = 3,
                            Rating = 4
                        });
                });

            modelBuilder.Entity("PublisherEntity", b =>
                {
                    b.Property<int>("IdPublisher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdPublisher");

                    b.ToTable("t_publisher");

                    b.HasData(
                        new
                        {
                            IdPublisher = 1,
                            Name = "Bloomsbury Publishing"
                        },
                        new
                        {
                            IdPublisher = 2,
                            Name = "Allen & Unwin"
                        },
                        new
                        {
                            IdPublisher = 3,
                            Name = "Bantam Books"
                        },
                        new
                        {
                            IdPublisher = 4,
                            Name = "Doubleday"
                        },
                        new
                        {
                            IdPublisher = 5,
                            Name = "Penguin Books"
                        },
                        new
                        {
                            IdPublisher = 6,
                            Name = "Simon & Schuster"
                        },
                        new
                        {
                            IdPublisher = 7,
                            Name = "Hachette Book Group"
                        },
                        new
                        {
                            IdPublisher = 8,
                            Name = "Macmillan Publishers"
                        },
                        new
                        {
                            IdPublisher = 9,
                            Name = "Random House"
                        },
                        new
                        {
                            IdPublisher = 10,
                            Name = "Éditions Gallimard"
                        });
                });

            modelBuilder.Entity("UserEntity", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUser");

                    b.ToTable("t_utilisateur");

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            Password = "hashed_password_123",
                            Role = "user",
                            Username = "alice_smith"
                        },
                        new
                        {
                            IdUser = 2,
                            Password = "hashed_password_456",
                            Role = "user",
                            Username = "bob_johnson"
                        },
                        new
                        {
                            IdUser = 3,
                            Password = "hashed_password_789",
                            Role = "admin",
                            Username = "carol_white"
                        },
                        new
                        {
                            IdUser = 4,
                            Password = "hashed_password_101",
                            Role = "user",
                            Username = "david_brown"
                        },
                        new
                        {
                            IdUser = 5,
                            Password = "hashed_password_202",
                            Role = "user",
                            Username = "emma_davis"
                        });
                });

            modelBuilder.Entity("BookEntity", b =>
                {
                    b.HasOne("AuthorEntity", "Author")
                        .WithMany("Books")
                        .HasForeignKey("FkAuthor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CategoryEntity", "Category")
                        .WithMany("Books")
                        .HasForeignKey("FkCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PublisherEntity", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("FkPublisher")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserEntity", "User")
                        .WithMany("Books")
                        .HasForeignKey("FkUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Publisher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CommentEntity", b =>
                {
                    b.HasOne("BookEntity", "Book")
                        .WithMany("Comments")
                        .HasForeignKey("FkBook")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserEntity", "User")
                        .WithMany("Comments")
                        .HasForeignKey("FkUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuthorEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookEntity", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("CategoryEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("PublisherEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("UserEntity", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
