// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_ASP_Book.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320142808_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AuthorEntity", b =>
                {
                    b.Property<int>("IdAuthor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdAuthor");

                    b.ToTable("t_author");
                });

            modelBuilder.Entity("BookEntity", b =>
                {
                    b.Property<int>("IdBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cover")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EditionYear")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FkAuthor")
                        .HasColumnType("int");

                    b.Property<int>("FkCategory")
                        .HasColumnType("int");

                    b.Property<int>("FkPublisher")
                        .HasColumnType("int");

                    b.Property<int>("FkUser")
                        .HasColumnType("int");

                    b.Property<int?>("NbPage")
                        .HasColumnType("int");

                    b.Property<string>("Passage")
                        .HasColumnType("longtext");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Resume")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdBook");

                    b.HasIndex("FkAuthor");

                    b.HasIndex("FkCategory");

                    b.HasIndex("FkPublisher");

                    b.HasIndex("FkUser");

                    b.ToTable("t_book");
                });

            modelBuilder.Entity("CategoryEntity", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdCategory");

                    b.ToTable("t_category");
                });

            modelBuilder.Entity("CommentEntity", b =>
                {
                    b.Property<int>("IdComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FkBook")
                        .HasColumnType("int");

                    b.Property<int>("FkUser")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("IdComment");

                    b.HasIndex("FkBook");

                    b.HasIndex("FkUser");

                    b.ToTable("t_comment");
                });

            modelBuilder.Entity("PublisherEntity", b =>
                {
                    b.Property<int>("IdPublisher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdPublisher");

                    b.ToTable("t_publisher");
                });

            modelBuilder.Entity("UserEntity", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUser");

                    b.ToTable("t_utilisateur");
                });

            modelBuilder.Entity("BookEntity", b =>
                {
                    b.HasOne("AuthorEntity", "Author")
                        .WithMany("Books")
                        .HasForeignKey("FkAuthor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CategoryEntity", "Category")
                        .WithMany("Books")
                        .HasForeignKey("FkCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublisherEntity", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("FkPublisher")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserEntity", "User")
                        .WithMany("Books")
                        .HasForeignKey("FkUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Publisher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CommentEntity", b =>
                {
                    b.HasOne("BookEntity", "Book")
                        .WithMany("Comments")
                        .HasForeignKey("FkBook")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserEntity", "User")
                        .WithMany("Comments")
                        .HasForeignKey("FkUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuthorEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookEntity", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("CategoryEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("PublisherEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("UserEntity", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
