version: "2"

services:
  frontend:
    build:
      context: ./Lecture-Passion
      dockerfile: Dockerfile
      args:
        VITE_MODE: development
        VITE_MSAL_CLIENT_ID: ${VITE_MSAL_CLIENT_ID}
        VITE_MSAL_TENANT_ID: ${VITE_MSAL_TENANT_ID}
        VITE_MSAL_REDIRECT_URI: ${VITE_MSAL_REDIRECT_URI}
    ports:
      - "3000:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0.30
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "127.0.0.1",
          "-u${DB_USER}",
          "-p${DB_PASSWORD}",
          "-e",
          "SELECT 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./API-ASP-Book
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${API_CONNECTION_STRING}
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
