name: "CI Frontend"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Lecture-Passion
    name: Run CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
        continue-on-error: true
      - name: Run tests
        run: npm run test:run
